set_property PACKAGE_PIN A8 [get_ports en]
set_property PACKAGE_PIN A9 [get_ports en_init]
set_property PACKAGE_PIN A10 [get_ports f_w_up]
set_property PACKAGE_PIN A11 [get_ports we_query]
set_property PACKAGE_PIN A13 [get_ports we_sen]
set_property IOSTANDARD LVCMOS18 [get_ports we_sen]
set_property IOSTANDARD LVCMOS18 [get_ports we_query]
set_property IOSTANDARD LVCMOS18 [get_ports f_w_up]
set_property IOSTANDARD LVCMOS18 [get_ports en_init]
set_property IOSTANDARD LVCMOS18 [get_ports en]

set_property MARK_DEBUG true [get_nets emb_bwd/_done_read_word]
