#!/bin/bash -f
# Vivado (TM) v2015.4.1 (64-bit)
#
# Filename    : MemN2N_TOP.sh
# Simulator   : Cadence Incisive Enterprise Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue May 10 13:35:49 +0900 2016
# IP Build 1427053 on Mon Dec  7 12:56:29 MST 2015 
#
# usage: MemN2N_TOP.sh [-help]
# usage: MemN2N_TOP.sh [-lib_map_path]
# usage: MemN2N_TOP.sh [-noclean_files]
# usage: MemN2N_TOP.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'MemN2N_TOP.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Script info
echo -e "MemN2N_TOP.sh - Script generated by export_simulation (Vivado v2015.4.1 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: MemN2N_TOP.sh [-help]\n\
Usage: MemN2N_TOP.sh [-lib_map_path]\n\
Usage: MemN2N_TOP.sh [-reset_run]\n\
Usage: MemN2N_TOP.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./MemN2N_TOP.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./MemN2N_TOP.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
     create_lib_mappings $2
     touch hdl.var
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
     touch hdl.var
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ncsim.key irun.key ncvlog.log ncvhdl.log compile.log elaborate.log simulate.log run.log waves.shm INCA_libs)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xbip_utils_v3_0_5 axi_utils_v2_0_1 xbip_pipe_v3_0_1 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_1 xbip_bram18k_v3_0_1 mult_gen_v12_0_10 floating_point_v7_0_11 xbip_dsp48_mult_v3_0_1 xbip_dsp48_multadd_v3_0_1 div_gen_v5_1_9 fifo_generator_v13_0_1 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_8)
  file="cds.lib"
  dir="ies"

  if [[ -e $file ]]; then
    rm -f $file
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi
  incl_ref="INCLUDE $lib_map_path/cds.lib"
  echo $incl_ref >> $file

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="DEFINE $lib $dir/$lib"
      echo $mapping >> $file
    fi
  done
}


# RUN_STEP: <compile>
compile()
{
  # Directory path for design sources and include directories (if any) wrt this path
  ref_dir="."
  # Command line options
  opts_ver="-64bit -messages -logfile ncvlog.log -append_log"
  opts_vhd="-64bit -V93 -RELAX -logfile ncvhdl.log -append_log"

  # Compile design files
  ncvhdl -work xbip_utils_v3_0_5 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_utils_v3_0_5/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

  ncvhdl -work axi_utils_v2_0_1 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/axi_utils_v2_0_1/hdl/axi_utils_v2_0_vh_rfs.vhd" \

  ncvhdl -work xbip_pipe_v3_0_1 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_pipe_v3_0_1/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_pipe_v3_0_1/hdl/xbip_pipe_v3_0.vhd" \

  ncvhdl -work xbip_dsp48_wrapper_v3_0_4 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_dsp48_wrapper_v3_0_4/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

  ncvhdl -work xbip_dsp48_addsub_v3_0_1 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_dsp48_addsub_v3_0_1/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_dsp48_addsub_v3_0_1/hdl/xbip_dsp48_addsub_v3_0.vhd" \

  ncvhdl -work xbip_bram18k_v3_0_1 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_bram18k_v3_0_1/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_bram18k_v3_0_1/hdl/xbip_bram18k_v3_0.vhd" \

  ncvhdl -work mult_gen_v12_0_10 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/mult_gen_v12_0_10/hdl/mult_gen_v12_0_vh_rfs.vhd" \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/mult_gen_v12_0_10/hdl/mult_gen_v12_0.vhd" \

  ncvhdl -work floating_point_v7_0_11 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/floating_point_v7_0_11/hdl/floating_point_v7_0_vh_rfs.vhd" \

  ncvhdl -work xbip_dsp48_mult_v3_0_1 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_dsp48_mult_v3_0_1/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_dsp48_mult_v3_0_1/hdl/xbip_dsp48_mult_v3_0.vhd" \

  ncvhdl -work xbip_dsp48_multadd_v3_0_1 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_dsp48_multadd_v3_0_1/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/xbip_dsp48_multadd_v3_0_1/hdl/xbip_dsp48_multadd_v3_0.vhd" \

  ncvhdl -work div_gen_v5_1_9 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/div_gen_v5_1_9/hdl/div_gen_v5_1_vh_rfs.vhd" \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/div_gen_v5_1_9/hdl/div_gen_v5_1.vhd" \
    "$ref_dir/../../../bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/div_32/sim/div_32.vhd" \

  ncvhdl -work fifo_generator_v13_0_1 $opts_vhd \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/fifo_32x1024/fifo_generator_v13_0_1/simulation/fifo_generator_vhdl_beh.vhd" \
    "$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/fifo_32x1024/fifo_generator_v13_0_1/hdl/fifo_generator_v13_0_rfs.vhd" \
    "$ref_dir/../../../bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/fifo_32x1024/sim/fifo_32x1024.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src" +incdir+"$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/fixed_mult.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/fixed_adder.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/MemN2N_emb_w_up_control.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/ram_sync.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/exp_fixed.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/counter.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/MemN2N_emb.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/MemN2N_phase_controller.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/MemN2N_fwd_path_controller.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/fully_connected_w_soft_max.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/decoder.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/accumulator_fixed.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/attention_memory.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src/MemN2N.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ip/MemN2N_TOP_MemN2N_0_0/sim/MemN2N_TOP_MemN2N_0_0.v" \

  ncvhdl -work lib_cdc_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ipstatic/lib_cdc_v1_0/hdl/src/vhdl/cdc_sync.vhd" \

  ncvhdl -work proc_sys_reset_v5_0_8 $opts_vhd \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/proc_sys_reset.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/MemN2N_TOP/ip/MemN2N_TOP_proc_sys_reset_0_0/sim/MemN2N_TOP_proc_sys_reset_0_0.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src" +incdir+"$ref_dir/../../../../MemN2N.srcs/sources_1/bd/MemN2N_TOP/ipshared/sspark/memn2n_v1_0/src" \
    "$ref_dir/../../../bd/MemN2N_TOP/ip/MemN2N_TOP_clk_wiz_0_1/MemN2N_TOP_clk_wiz_0_1_clk_wiz.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/ip/MemN2N_TOP_clk_wiz_0_1/MemN2N_TOP_clk_wiz_0_1.v" \
    "$ref_dir/../../../bd/MemN2N_TOP/hdl/MemN2N_TOP.v" \


  ncvlog $opts_ver -work xil_defaultlib \
    "glbl.v"

}

# RUN_STEP: <elaborate>
elaborate()
{
  opts="-64bit -relax -access +rwc -messages -logfile elaborate.log -timescale 1ps/1ps"
  libs="-libname unisims_ver -libname unimacro_ver -libname secureip -libname xbip_utils_v3_0_5 -libname axi_utils_v2_0_1 -libname xbip_pipe_v3_0_1 -libname xbip_dsp48_wrapper_v3_0_4 -libname xbip_dsp48_addsub_v3_0_1 -libname xbip_bram18k_v3_0_1 -libname mult_gen_v12_0_10 -libname floating_point_v7_0_11 -libname xbip_dsp48_mult_v3_0_1 -libname xbip_dsp48_multadd_v3_0_1 -libname div_gen_v5_1_9 -libname fifo_generator_v13_0_1 -libname xil_defaultlib -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_8"
  ncelab $opts xil_defaultlib.MemN2N_TOP xil_defaultlib.glbl $libs
}

# RUN_STEP: <simulate>
simulate()
{
  opts="-64bit -logfile simulate.log"
  ncsim $opts xil_defaultlib.MemN2N_TOP -input simulate.do
}
# Script usage
usage()
{
  msg="Usage: MemN2N_TOP.sh [-help]\n\
Usage: MemN2N_TOP.sh [-lib_map_path]\n\
Usage: MemN2N_TOP.sh [-reset_run]\n\
Usage: MemN2N_TOP.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
